ha:
  common:
    url: http://127.0.0.1:8123
    url-ws: ws://127.0.0.1:8123/api/websocket
    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJhMmZlZmQyMjM0OGQ0ZDkzODA3ZmQ5ZGIwMWUwZDUwOSIsImlhdCI6MTY3NzgxMjU2NCwiZXhwIjoxOTkzMTcyNTY0fQ.fHpxT44K9bSG5jxIdqzPNpjyeco_q0Uh_hONQS9pksE
